# Generated by Django 4.2.4 on 2023-08-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
