# Generated by Django 4.2.4 on 2023-08-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_user_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("text", models.CharField(max_length=400)),
            ],
        ),
    ]
