# Generated by Django 4.2.4 on 2023-08-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_user_posts"),
        ("content", "0005_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.user",
            ),
        ),
    ]
